### ISSUE TITLE
username and password accessors return undef when Config::Identity is used

### ISSUE THREAD

**Issue by mannih** [packy/JIRA-REST-Class#6]
I have a file $HOME/.jira containing my jira credentials.
I (successfully) use JIRA::REST::Class to access my JIRA instance.
But when calling the username accessor, it will simply return undef.
Looking at the code, I'm not sure how the username field is supposed to be populated when Config::Identity is used.

**Comment by mannih** [comment]
Having looked at the code some more, the specific problem seems to be that JIRA::REST figures out password and username and then just throws them away after building up the Authorization header. Which makes sense. @gnustavo might be nice enough to put a little accessor into JIRA::REST to at least make the username parameter accessible. Or even all the %args JIRA::REST is using?

**Comment by packy** [comment]
Hmmm. I thought I had that already solved, considering I have in my POD that the username accessor works even when Config::Identity is used.  I may have code in a branch that I never merged into the trunk.

And @gnustavo has been very nice in making upstream changes, I'd rather not depend on them. Give me a little bit and I'll see why I thought I already had this solved.

**Comment by mannih** [comment]
Thank you for looking into this! And thank you for you amazing set of JIRA-modules. Using those, what I'm doing feels like playing with lego. All I have to do is find the correct pieces.

Yes, you do sound very optimistic in the POD. I wouldn't have opened an issue otherwise ;-)

What I'm actually trying to do is "if this issue isn't assigned to me, assign it to me". Which isn't easy when you don't know who you are.

**Comment by mannih** [comment]
Ah! I found something: JIRA::REST::Class::Mixins::JIRA_REST() reconstructs username and password. But unfortunately not when _JIRA_REST_version_has_named_parameters. However, I'm not sure where $args is supposed to end up.

**Comment by gnustavo** [comment]
@mannih , wouldn't the [/api/2/myself](https://docs.atlassian.com/jira/REST/server/#api/2/myself) method help you to know who you are?

**Comment by packy** [comment]
Ooh. That would be even better than caching whatever we used. I'll modify JRC to make that call.

**Comment by packy** [comment]
Ok, fix is complete, but only half of it is in the version 0.11 release of the module. I added a new method on the top-level JIRA::REST::Class class called user_object() that returns the current user as a JIRA::REST::Class::User object, and if the JIRA::REST::Class object doesn't have a cached username, it calls that to get the username.  I pushed that in the version 0.11 release because that's what you really needed.

This morning, I poked through the Mixins module and found the code you were referring to, so I moved it to unpack the password from the Authorization header if the object doesn't have it cached already.  This will be in the next official release of the module, but if anybody needs it, they can install the module from GItHub and try it out.

Thanks a lot for this bug report, @mannih!  I've since changed jobs, and I'm not using these modules to wrangle my JIRA instance into submission, so I'm not actively working on it.  If you have any feature requests, please pass them along! I want to keep working on this, but without needing to add features for my own use, there isn't anything pushing me to do so. Having features that would be useful to other people would be just the incentive I need.
